name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    permissions: # Advanced permission for ArtiomTr/jest-coverage-report-action
      checks: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install

      - name: Publish Coverage Report to Coveralls.io
        if: always() && hashFiles('coverage/**') != ''
        uses: coverallsapp/github-action@v2

      - name: Testspace client install & config
        id: testspace_init
        if: always() && hashFiles('test-results/**') != ''
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}

      - name: Testspace push test content
        if: always() && (steps.testspace_init.outcome == 'success')
        run: testspace "./test-results/*.xml" --link=coveralls

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 1000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
